on:
  - push
  # - pull_request

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    services:
      rqlite-js:
        image: rqlite/rqlite:5.12.1
        ports:
          - 4001:4001
          - 4002:4002

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: corepack enable

      # - uses: pnpm/action-setup@v2.2.4
      #   name: Install pnpm
      #   id: pnpm-install
      #   with:
      #     version: 7
      #     run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: |
          pnpm run build-all
          pnpm run test-build
          pnpm run test-build-integrations
